Docs/issue 430 update technical documentation to reflect current project status
ProjectEvergreen/greenwood pull request #452
Opened 2020-12-22 23:28 UTC by thescientist13

## Related Issue
resolves #430 

> _**Note**: this captures the current state of things.  Going forward PRs will need to update docs as functionality and features are restored._

## Summary of Changes
1. Lerna doesnt bump _www/packages,json_ on custom pre release versions, had to bump myself fyi
1. Updates _Docs_ and _Getting Started_ sections to reflect current state of the project (including marking things as **Coming Soon** and commenting out the docs where the feature is missing now)
1. Left _Plugins_ section alone since there is. #450 open now, where we should start documenting all new features going forward as PRs come in for them
1. Removed need to escape `$` and ``` in code fences (it just works now 🥳 )
1. Deleted "dead" code
1. Left a comment on thoughts about layout and organization here
1. fixed some typos, probably added some new typos, lol

## TODO
1. [ ] Confirm environment variables are captured correctly in guides, after unescaping
1. [ ] need track restoring `config.publicPath` or verify it still works
1. [ ] need to track restoring `config.devServer.host` (not actually be used in `serve` lifecycle)
1. [ ] Bug around how `<link>` tags are detected.  Current assumption is wrong, as there is no closing `</link>` tag involved
1. [ ] Proof read, etc

2020-12-23 01:21 UTC, aholtzman commented on www/pages/docs/css-and-images.md
> +> If you like your all-the-things-in-JS approach, Greenwood can be extended with [plugins](/plugins/) to support "webpack" like behavior as seeb in the below example:
nit: 'seen'

2020-12-23 17:50 UTC, thescientist13 commented
Noticing on the target branch that the headings aren't looking correct, so just a note to self here to review all those and / or fix them if present here.
<img width="483" alt="Screen Shot 2020-12-23 at 12 44 40 PM" src="https://user-images.githubusercontent.com/895923/103024215-67a27400-451d-11eb-80ba-642f44800232.png">

2020-12-28 17:18 UTC, thescientist13 commented
@aholtzman 
Could you do me a favor and review these two pages?  Now that we don't need to escape `$` and the like in our markdown, I'm not sure what the correct escaping / syntax is needed (if any) for these examples to make sure they are correct.  Thanks!
- https://github.com/ProjectEvergreen/greenwood/pull/452/files?short_path=72e5bc3#diff-72e5bc3e9a1ffc288ce9191d15a7052344dec844e369ee03bdb2fbcaba4ccd9f
- https://github.com/ProjectEvergreen/greenwood/pull/452/files?short_path=8c80b44#diff-8c80b44902cf615bc607664910f3abc7bad8617ff5c4eeaa0f5a18f623936a36

2020-12-28 20:01 UTC, aholtzman approved these changes
changes to escaped charters looks correct.

2020-12-28 20:35 UTC, hutchgrant requested changes
This is an excellent update of the docs with some spelling mistakes here and there.  I don't agree with the spacing of headings in general, which is also somehow different on `getting-started/index.md` . The ordered lists need a margin as well as the `<code />` elements need a different text color, make sure the selector is `p > code` and not just `code` as our prismjs code highlights will be affected otherwise.

2020-12-28 20:35 UTC, hutchgrant commented on www/pages/docs/index.md
> +To continue learning more abuut Greenwood, please feel free to browse the other sections of our documentation.
`abuut`

2020-12-28 20:35 UTC, hutchgrant commented on www/pages/docs/layouts.md
> +Pages in your project will generally want a template so you can control the output of the HTML and include all your own custom components and styles.  By default alll pages will default to looking fo
`alll`

2020-12-28 20:35 UTC, hutchgrant commented on www/pages/docs/front-matter.md
>  ### Template
I think it might be worth linking to the front-matter docs #page-template as well. This way both link to each as they both involve each other.

2020-12-28 20:35 UTC, hutchgrant commented on www/pages/docs/markdown.md
> +-->
This is visible on page `-->`

2020-12-28 20:35 UTC, hutchgrant commented on www/pages/getting-started/index.md
>  To get things started, we first want to make sure everyone can get their first project up and running as easily and quickly as possible, and so through this guide, we will help walk you through every
The ordered list needs a margin of like 20px it looks out of place.

2020-12-28 20:35 UTC, hutchgrant commented on www/pages/getting-started/index.md
>  ## Your First Project
There are massive margins for top and bottom on heading within the docs but not apparent on this page? Needs to be identical and reasonable gap between sections.

2020-12-28 20:35 UTC, hutchgrant commented on www/pages/getting-started/index.md
> +First off, thank you for taking the time to check out **Greenwood**!  As a tool, we hope that you find Greenwood to provide a productive and frictionless developer experience for you that results in
`perfmant applicatiot`

2020-12-28 21:00 UTC, thescientist13 commented
Thanks for the feedback @aholtzman / @hutchgrant !  🙏 

@hutchgrant 
I will definitely clean up more of those typos, but my plan has been to capture restoring website functionality / behavior to  #432, as I really wanted to limit the scope of this just to the documentation itself so we don't get further behind in keeping the content up to date as more PRs land.

2020-12-30 16:11 UTC, merged