Chore/project docs update
ProjectEvergreen/greenwood pull request #798
Opened 2021-11-09 15:19 UTC by thescientist13

## Related Issue
N / A

## Summary of Changes
Updated CONTRIBUTING.md with
1. _Project Management_ section covering Discussions and Project boards
1. Added _Release Management_ section
1. Did a little re-structuring of headings

2021-11-11 00:59 UTC, hutchgrant requested changes
spelling errors, typos, grammer, and a few run-ons.

2021-11-11 00:59 UTC, hutchgrant commented on .github/CONTRIBUTING.md
> +### Project Boardss
Boards

2021-11-11 00:59 UTC, hutchgrant commented on .github/CONTRIBUTING.md
> +> _We encourage all contributors to have first read about the project's vision and motivation's on the website's [About page](https://www.greenwoodjs.io/about/).  Greenwood is opinionated in the sens
it's ? not it is. Contraction or no?

2021-11-11 00:59 UTC, hutchgrant commented on .github/CONTRIBUTING.md
> +> _We encourage all contributors to have first read about the project's vision and motivation's on the website's [About page](https://www.greenwoodjs.io/about/).  Greenwood is opinionated in the sens
"for the web platform" sounds weird maybe just "for the web ? "

2021-11-11 00:59 UTC, hutchgrant commented on .github/CONTRIBUTING.md
> +> _We encourage all contributors to have first read about the project's vision and motivation's on the website's [About page](https://www.greenwoodjs.io/about/).  Greenwood is opinionated in the sens
That ^^ sentence kinda run-on

2021-11-11 00:59 UTC, hutchgrant commented on .github/CONTRIBUTING.md
> +Our [sequentially named project boards](https://github.com/ProjectEvergreen/greenwood/projects) help us organize work in quartery buckets with a small handful of "top line" goals and objectives we wo
quarterly ? I think you mean?

oppourtunities  ?  Opportunities

2021-11-11 00:59 UTC, hutchgrant commented on .github/CONTRIBUTING.md
> +We encourage discussions as we believe it is better to hash out technical discussions and proposals ahead of time since coding and reviewing PRs is very time consuming and as maintainer's, we want to
"it is" can probably go with contraction instead.  Also this is a single sentence and it's long.

2021-11-11 00:59 UTC, hutchgrant commented on .github/CONTRIBUTING.md
> +We like to reserve issues for features and requests that are more or less "shovel" ready.  This could include prior discussions with the team or coming over from an existing Disussion.
capital D on discussion not needed

2021-11-11 00:59 UTC, hutchgrant commented on .github/CONTRIBUTING.md
> +## Suppplemental Infomration
information

2021-11-11 00:59 UTC, hutchgrant commented on .github/CONTRIBUTING.md
> +Lerna is used to manage the publishing of packages within the workspace.  Assuming your are logged into **npm** locally and have 2FA access to publish, the command to run is
"your are"  - you're

2021-11-11 00:59 UTC, hutchgrant commented on .github/ISSUE_TEMPLATE.md
> +Include relevant code samples, example snippets, benefits, complexity, etc.  For feature requests, please make sure to provide an actionable outcome.  If you're unsure what qualifies, please consider
"start6ing"  and "Discussion"

2021-11-18 15:39 UTC, thescientist13 commented
Think I got em all @hutchgrant , thanks for the keen review.  🔍 👀

2021-11-18 15:39 UTC, merged